export const metadata = {
    title: 'Blogs List',
    description: 'Generated by Blogs List',
}

export default function BlogsLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <>
            {children}
        </>


    )
}
