
export const metadata = {
    title: 'Users List',
    description: 'Generated by Users List',
}

export default function UsersLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <>
            {children}
        </>


    )
}
